### PR TITLE
Hey bro! look!

### PR DESCRIPTION
**Pull request by C0olSk3leton95**
The intro.

### CODE REVIEW

**Comment by ChaboCode** [comment]
So you founded out how to made changes. But ensure to do changes that can make improvements to the actual repo.

**Comment by Jcw87** [comment]
Looks like you still don't understand what pull requests are for.

**Comment by ChaboCode** [comment]
> Looks like you still don't understand what pull requests are for.

Hey, dont be that rude. Maybe he is learning how to do github stuff.

**Comment by Jcw87** [comment]
Have you noticed how many completely useless pull requests I get?

These PRs break the game:
https://github.com/Jcw87/c2-sans-fight/pull/24
https://github.com/Jcw87/c2-sans-fight/pull/26
https://github.com/Jcw87/c2-sans-fight/pull/60

This PR changes the music
https://github.com/Jcw87/c2-sans-fight/pull/25

This PR changes all of the attacks to some custom variant that isn't even his own
https://github.com/Jcw87/c2-sans-fight/pull/38

This PR changes my readme.md file to the same as above
https://github.com/Jcw87/c2-sans-fight/pull/43

This PR tries (and fails) to create an uber cheat item
https://github.com/Jcw87/c2-sans-fight/pull/52

This PR replaces my google analytics with someone else's, and demands that I merge it.
https://github.com/Jcw87/c2-sans-fight/pull/56

Then we have that last PR made by this guy where he replaces an image with a less accurate one.
https://github.com/Jcw87/c2-sans-fight/pull/74

And now we have this PR, which adds a file that does absolutely nothing!

Most of the people who made these PRs clearly have had no experience with git or github at all. It isn't about being rude or polite, it's about minimizing how much of my time is wasted by this shit.

**Comment by ChaboCode** [comment]
well, I have time that I can use to close useless PRs, maybe I can help you with that.

**Comment by C0olSk3leton95** [comment]
Yeah..

Em Seg, 13 de jul de 2020 23:58, Jcw87 <notifications@github.com> escreveu:

**Pull request closed without merging**
