### PR TITLE
Sans_intro.csv

### PR DESCRIPTION
**Pull request by israelita95**
Yeah, I'm trying to see this

### CODE REVIEW

**Comment by ChaboCode** [comment]
You don't like his first attack, aren't you?

**Comment by biomseed** [comment]
There have been so many pull requests that go against the game's purpose. These people don't know how to use Github, and probably think pull requests are some modding thing.

**Comment by israelita95** [comment]
I know how to make customized attacks, I just don't know how to use github,
friend.

Em qui, 5 de nov de 2020 13:33, Saul Chavez Sanchez <
notifications@github.com> escreveu:

**Comment by israelita95** [comment]
I just want to know how you use this as a template or clone, lmao ... And
still have a gh-page to see the changes.

Em qui, 5 de nov de 2020 15:21, biomseed <notifications@github.com>
escreveu:

**Comment by Jcw87** [comment]
@israelita95 you will find the answers you seek [here](http://letmegooglethat.com/?q=gh+pages).

**Comment by Jcw87** [comment]
@israelita95 Also, you don't need to use gh pages to preview a change. You can just run it locally. Depending on what web browser you use, you may be able to just open the html file and it will work. If it doesn't, literally any http server will make it work.

**Pull request closed without merging**
